/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'displayOrder' : bigint,
  'name' : string,
  'description' : string,
  'coverImage' : string,
}
export interface CustomerSelection {
  'id' : bigint,
  'customerName' : string,
  'submittedAt' : bigint,
  'email' : string,
  'designId' : bigint,
  'message' : string,
  'brideGroomNames' : string,
  'phone' : string,
  'designName' : string,
  'eventDate' : string,
}
export interface Design {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'description' : string,
  'price' : string,
  'videoUrl' : string,
}
export interface SiteSettings {
  'instagramLink' : string,
  'tagline' : string,
  'whatsappLink' : string,
  'twitterLink' : string,
  'contactEmail' : string,
  'facebookLink' : string,
  'contactPhone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'adminSignup' : ActorMethod<[string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], undefined>,
  'createCategory' : ActorMethod<[string, string, bigint, string], Category>,
  'createCategoryWithSession' : ActorMethod<
    [string, string, string, bigint, string],
    Category
  >,
  'createDesign' : ActorMethod<
    [bigint, string, string, string, string],
    Design
  >,
  'createDesignWithSession' : ActorMethod<
    [string, bigint, string, string, string, string],
    Design
  >,
  'createSelection' : ActorMethod<
    [bigint, string, string, string, string, string, string, string],
    CustomerSelection
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteCategoryWithSession' : ActorMethod<[string, bigint], undefined>,
  'deleteDesign' : ActorMethod<[bigint], undefined>,
  'deleteDesignWithSession' : ActorMethod<[string, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getDesign' : ActorMethod<[bigint], [] | [Design]>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'initializeSeedData' : ActorMethod<[string], undefined>,
  'isAdminSetup' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listDesigns' : ActorMethod<[], Array<Design>>,
  'listDesignsByCategory' : ActorMethod<[bigint], Array<Design>>,
  'listSelections' : ActorMethod<[], Array<CustomerSelection>>,
  'listSelectionsWithSession' : ActorMethod<[string], Array<CustomerSelection>>,
  'requestAdminOtp' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'updateCategoryWithSession' : ActorMethod<
    [string, bigint, string, string, bigint, string],
    undefined
  >,
  'updateDesign' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    undefined
  >,
  'updateDesignWithSession' : ActorMethod<
    [string, bigint, bigint, string, string, string, string],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateSiteSettingsWithSession' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'verifyAdminOtp' : ActorMethod<[string, string], string>,
  'verifyAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];