/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : IDL.Text,
});
export const Design = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const CustomerSelection = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'designId' : IDL.Nat,
  'message' : IDL.Text,
  'brideGroomNames' : IDL.Text,
  'phone' : IDL.Text,
  'designName' : IDL.Text,
  'eventDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'instagramLink' : IDL.Text,
  'tagline' : IDL.Text,
  'whatsappLink' : IDL.Text,
  'twitterLink' : IDL.Text,
  'contactEmail' : IDL.Text,
  'facebookLink' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'adminSignup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Category],
      [],
    ),
  'createCategoryWithSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Category],
      [],
    ),
  'createDesign' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Design],
      [],
    ),
  'createDesignWithSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Design],
      [],
    ),
  'createSelection' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [CustomerSelection],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteCategoryWithSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteDesign' : IDL.Func([IDL.Nat], [], []),
  'deleteDesignWithSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'initializeSeedData' : IDL.Func([IDL.Text], [], []),
  'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'listDesignsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Design)], ['query']),
  'listSelections' : IDL.Func([], [IDL.Vec(CustomerSelection)], ['query']),
  'listSelectionsWithSession' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerSelection)],
      [],
    ),
  'requestAdminOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateCategoryWithSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateDesign' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateDesignWithSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSiteSettingsWithSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'verifyAdminOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : IDL.Text,
  });
  const Design = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const CustomerSelection = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'designId' : IDL.Nat,
    'message' : IDL.Text,
    'brideGroomNames' : IDL.Text,
    'phone' : IDL.Text,
    'designName' : IDL.Text,
    'eventDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'instagramLink' : IDL.Text,
    'tagline' : IDL.Text,
    'whatsappLink' : IDL.Text,
    'twitterLink' : IDL.Text,
    'contactEmail' : IDL.Text,
    'facebookLink' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'adminSignup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Category],
        [],
      ),
    'createCategoryWithSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Category],
        [],
      ),
    'createDesign' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Design],
        [],
      ),
    'createDesignWithSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Design],
        [],
      ),
    'createSelection' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [CustomerSelection],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteCategoryWithSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteDesign' : IDL.Func([IDL.Nat], [], []),
    'deleteDesignWithSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'initializeSeedData' : IDL.Func([IDL.Text], [], []),
    'isAdminSetup' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'listDesignsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Design)], ['query']),
    'listSelections' : IDL.Func([], [IDL.Vec(CustomerSelection)], ['query']),
    'listSelectionsWithSession' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerSelection)],
        [],
      ),
    'requestAdminOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateCategoryWithSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateDesign' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDesignWithSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSiteSettingsWithSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'verifyAdminOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'verifyAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };